# Generated by Django 4.2.4 on 2023-08-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orga", "0005_remove_user_address_address_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="zipcode",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(default="", max_length=255),
        ),
    ]
